language: objective-c
osx_image: xcode10

jobs:
 include:
   - script: xcodebuild clean build test -project SwiftCards.xcodeproj -scheme SwiftCards -destination "platform=iOS Simulator,name=iPhone 8,OS=11.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
